# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

projectName = File.basename(Dir.glob("../*.xcodeproj")[0], ".*")
appVersion = get_version_number(xcodeproj: "#{projectName}.xcodeproj")
time = Time.now.strftime("%m%d%H%M")


platform :ios do

  lane :dev do
  	configuration = "Debug"

  	build_app(
      export_method: "development",
      configuration: configuration,
      output_directory: "ipas/" + configuration + "/" + appVersion,
      output_name: projectName + "_" + time,
    )

  end

end
